export const BOOKS = [
  {
    id: '1',
    title: 'The Life and Adventures of Robinson Crusoe',
    author: 'Daniel Defoe',
    cover: 'https://picsum.photos/seed/robinson/400/400',
    description: 'Robinson Crusoe is a novel by Daniel Defoe, first published on 25 April 1719. The first edition credited the work\'s protagonist Robinson Crusoe as its author, leading many readers to believe he was a real person and the book a travelogue of true incidents.',
    status: 'completed',
    genre: 'Adventure',
    dateAdded: '2023-01-15',
  },
  {
    id: '2',
    title: 'The Good Soldier',
    author: 'Ford Madox Ford',
    cover: 'https://picsum.photos/seed/soldier/400/400',
    description: 'The Good Soldier is a 1915 novel by British writer Ford Madox Ford. It is set just before World War I and chronicles the tragedy of Edward Ashburnham, the soldier to whom the title refers, and his own seemingly perfect marriage and that of his two American friends.',
    status: 'unread',
    genre: 'Classic',
    dateAdded: '2023-02-20',
  },
  {
    id: '3',
    title: 'The Brothers Karamazov',
    author: 'Fyodor Dostoevsky',
    cover: 'https://picsum.photos/seed/brothers/400/400',
    description: 'The Brothers Karamazov is the final novel by the Russian author Fyodor Dostoevsky. Dostoevsky spent nearly two years writing The Brothers Karamazov, which was published as a serial in The Russian Messenger from January 1879 to November 1880.',
    status: 'reading',
    genre: 'Philosophy',
    dateAdded: '2023-03-10',
  },
  {
    id: '4',
    title: 'Crime and Punishment',
    author: 'Fyodor Dostoevsky',
    cover: 'https://picsum.photos/seed/crime/400/400',
    description: 'Crime and Punishment is a novel by the Russian author Fyodor Dostoevsky. It was first published in the literary journal The Russian Messenger in twelve monthly installments during 1866. It is the second of Dostoevsky\'s full-length novels.',
    status: 'unread',
    genre: 'Philosophy',
    dateAdded: '2023-04-05',
  },
  {
    id: '5',
    title: 'The War of the Worlds',
    author: 'H. G. Wells',
    cover: 'https://picsum.photos/seed/war/400/400',
    description: 'The War of the Worlds is a science fiction novel by English author H. G. Wells, first serialised in 1897 by Pearson\'s Magazine in the UK and by Cosmopolitan magazine in the US. The novel\'s first appearance in hardcover was in 1898 from publisher William Heinemann of London.',
    status: 'completed',
    genre: 'Sci-Fi',
    dateAdded: '2023-05-12',
  },
  {
    id: '6',
    title: 'Moby Dick',
    author: 'Herman Melville',
    cover: 'https://picsum.photos/seed/moby/400/400',
    description: 'Moby-Dick; or, The Whale is an 1851 novel by American writer Herman Melville. The book is the sailor Ishmael\'s narrative of the obsessive quest of Ahab, captain of the whaling ship Pequod, for revenge on Moby Dick, the giant white sperm whale.',
    status: 'unread',
    genre: 'Adventure',
    dateAdded: '2023-06-18',
  },
  {
    id: '7',
    title: 'The Call of the Wild',
    author: 'Jack London',
    cover: 'https://picsum.photos/seed/wild/400/400',
    description: 'The Call of the Wild is a short adventure novel by Jack London, published in 1903 and set in Yukon, Canada, during the 1890s Klondike Gold Rush, when strong sled dogs were in high demand. The central character of the novel is a dog named Buck.',
    status: 'reading',
    genre: 'Adventure',
    dateAdded: '2023-07-22',
  },
  {
    id: '8',
    title: "Grimms' Fairy Tales",
    author: 'Jacob Grimm, Wilhelm Grimm',
    cover: 'https://picsum.photos/seed/grimm/400/400',
    description: 'Grimms\' Fairy Tales, originally known as the Children\'s and Household Tales, is a German collection of fairy tales first published in 1812 by the Grimm brothers, Jacob and Wilhelm.',
    status: 'completed',
    genre: 'Fantasy',
    dateAdded: '2023-08-30',
  },
  {
    id: '9',
    title: "Gulliver's Travels into Several Remote Nations of the World",
    author: 'Jonathan Swift',
    cover: 'https://picsum.photos/seed/gulliver/400/400',
    description: 'Gulliver\'s Travels, or Travels into Several Remote Nations of the World. In Four Parts. By Lemuel Gulliver, First a Surgeon, and then a Captain of Several Ships is a prose satire of 1726 by the Anglo-Irish writer and clergyman Jonathan Swift.',
    status: 'unread',
    genre: 'Adventure',
    dateAdded: '2023-09-14',
  },
  {
    id: '10',
    title: 'A Journey to the Center of the Earth',
    author: 'Jules Verne',
    cover: 'https://picsum.photos/seed/center/400/400',
    description: 'Journey to the Center of the Earth is a classic science fiction novel by Jules Verne. It was first published in French in 1864, then reissued in 1867 in a revised and expanded edition.',
    status: 'reading',
    genre: 'Sci-Fi',
    dateAdded: '2023-10-25',
  },
  {
    id: '11',
    title: 'Twenty Thousand Leagues under the Sea',
    author: 'Jules Verne',
    cover: 'https://picsum.photos/seed/sea/400/400',
    description: 'Twenty Thousand Leagues Under the Seas: A World Tour Underwater is a classic science fiction adventure novel by French writer Jules Verne; it was first published in 1870.',
    status: 'completed',
    genre: 'Sci-Fi',
    dateAdded: '2023-11-02',
  },
  {
    id: '12',
    title: 'The Wonderful Wizard of Oz',
    author: 'L. Frank Baum',
    cover: 'https://picsum.photos/seed/oz/400/400',
    description: 'The Wonderful Wizard of Oz is an American children\'s novel written by author L. Frank Baum and illustrated by W. W. Denslow, originally published by the George M. Hill Company in Chicago on May 17, 1900.',
    status: 'unread',
    genre: 'Fantasy',
    dateAdded: '2023-12-20',
  },
];
